"""Gaussian cube read/write for NICS and ICSS fields.

Cubes are written beside the ORCA output in a ``<base>_nics_cubes`` folder and
reused on the next open, so a field is computed once and stays available to
any other cube viewer.
"""

import logging
import os
import re

try:
    import numpy as np
except ImportError:  # CI installs pytest only
    np = None

BOHR_PER_ANGSTROM = 1.0 / 0.52917720859

ATOMIC_NUMBERS = {
    "H": 1,
    "He": 2,
    "Li": 3,
    "Be": 4,
    "B": 5,
    "C": 6,
    "N": 7,
    "O": 8,
    "F": 9,
    "Ne": 10,
    "Na": 11,
    "Mg": 12,
    "Al": 13,
    "Si": 14,
    "P": 15,
    "S": 16,
    "Cl": 17,
    "Ar": 18,
    "K": 19,
    "Ca": 20,
    "Sc": 21,
    "Ti": 22,
    "V": 23,
    "Cr": 24,
    "Mn": 25,
    "Fe": 26,
    "Co": 27,
    "Ni": 28,
    "Cu": 29,
    "Zn": 30,
    "Ga": 31,
    "Ge": 32,
    "As": 33,
    "Se": 34,
    "Br": 35,
    "Kr": 36,
    "Ru": 44,
    "Rh": 45,
    "Pd": 46,
    "Ag": 47,
    "Sn": 50,
    "Sb": 51,
    "Te": 52,
    "I": 53,
    "Xe": 54,
    "Pt": 78,
    "Au": 79,
    "Hg": 80,
    "Pb": 82,
    "Bi": 83,
}


def cube_dir_for(out_path):
    """``<output>_nics_cubes`` beside the ORCA file (not created here)."""
    if not out_path:
        return None
    base = os.path.splitext(os.path.basename(out_path))[0]
    return os.path.join(
        os.path.dirname(os.path.abspath(out_path)), f"{base}_nics_cubes"
    )


def cube_path_for(out_path, component, tag=None):
    """Path of the cached cube for a component ('iso' / 'zz') and optional tag."""
    folder = cube_dir_for(out_path)
    if folder is None:
        return None
    base = os.path.splitext(os.path.basename(out_path))[0]
    suffix = f"_{_sanitize(tag)}" if tag else ""
    return os.path.join(folder, f"{base}_NICS_{_sanitize(component)}{suffix}.cube")


def _sanitize(text):
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", str(text)).strip("_")
    while "__" in safe:
        safe = safe.replace("__", "_")
    return safe or "field"


def stamp_line(version, component, shape, axis=None, source=None, axis_mode=None):
    """The second cube comment line, recording how the field was made."""
    parts = [
        f"ORCA NICS Analyzer v{version}",
        f"component={component}",
        f"grid={'x'.join(str(int(n)) for n in shape)}",
    ]
    if axis is not None:
        parts.append("axis=" + ",".join(f"{float(v):.6f}" for v in axis))
    if axis_mode is not None:
        parts.append(f"axis_mode={axis_mode}")
    if source:
        parts.append(f"source={os.path.basename(source)}")
    return " ".join(parts)


def read_generation_settings(filepath):
    """What a cached cube was written with; unknown fields come back None."""
    info = {
        "version": None, "component": None, "grid": None, "axis": None, "axis_mode": None
    }
    try:
        with open(filepath, "r", encoding="utf-8", errors="replace") as fh:
            fh.readline()
            stamp = fh.readline()
    except OSError as e:
        logging.warning("[orca_nics_analyzer] cube header %s: %s", filepath, e)
        return info

    m = re.search(r"ORCA NICS Analyzer v(\S+)", stamp)
    if m:
        info["version"] = m.group(1)
    m = re.search(r"component=(\S+)", stamp)
    if m:
        info["component"] = m.group(1)
    m = re.search(r"grid=(\d+)x(\d+)x(\d+)", stamp)
    if m:
        info["grid"] = tuple(int(g) for g in m.groups())
    m = re.search(r"axis=([-0-9.]+),([-0-9.]+),([-0-9.]+)", stamp)
    if m:
        info["axis"] = tuple(float(g) for g in m.groups())
    m = re.search(r"axis_mode=(\S+)", stamp)
    if m:
        info["axis_mode"] = m.group(1)
    return info


def write_cube(
    path,
    data,
    origin,
    vectors,
    symbols=(),
    coords=(),
    comment="NICS field (ppm)",
    stamp="",
):
    """Write *data* as a cube. ``origin``/``vectors``/``coords`` are Angstrom.

    ``vectors`` are the three voxel step vectors, which for a ring-frame grid
    are not axis-aligned — the cube format carries them verbatim, so no
    resampling onto a lab-aligned box is needed.
    """
    arr = np.asarray(data, dtype=float)
    if arr.ndim != 3:
        raise ValueError(f"cube data must be 3D, got shape {arr.shape}")

    folder = os.path.dirname(path)
    if folder:
        os.makedirs(folder, exist_ok=True)

    org = np.asarray(origin, dtype=float) * BOHR_PER_ANGSTROM
    vecs = np.asarray(vectors, dtype=float) * BOHR_PER_ANGSTROM
    atoms = list(zip(symbols, coords))

    lines = [comment, stamp or "generated by ORCA NICS Analyzer"]
    lines.append(f"{len(atoms):5d}{org[0]:12.6f}{org[1]:12.6f}{org[2]:12.6f}")
    for n, v in zip(arr.shape, vecs):
        lines.append(f"{n:5d}{v[0]:12.6f}{v[1]:12.6f}{v[2]:12.6f}")
    for sym, xyz in atoms:
        z = ATOMIC_NUMBERS.get(str(sym).rstrip(":"), 0)
        p = np.asarray(xyz, dtype=float) * BOHR_PER_ANGSTROM
        lines.append(f"{z:5d}{float(z):12.6f}{p[0]:12.6f}{p[1]:12.6f}{p[2]:12.6f}")

    # Gaussian's data order: x slowest, z fastest, six values per line.
    flat = np.nan_to_num(arr, nan=0.0).ravel(order="C")
    for start in range(0, flat.size, 6):
        lines.append("".join(f"{v:13.5E}" for v in flat[start : start + 6]))

    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    return path


def read_cube(path):
    """Read a cube written by this plugin (or any standard writer).

    Returns ``{data, origin, vectors, symbols, coords, comment, stamp}`` with
    lengths back in Angstrom.
    """
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        text = fh.read()
    tokens = text.splitlines()
    comment, stamp = tokens[0], tokens[1]

    header = tokens[2].split()
    natoms = int(header[0])
    origin = np.array([float(v) for v in header[1:4]])
    # A negative atom count marks an orbital cube: the counts stay positive and
    # an extra DSET_IDS line follows the atom block.
    has_dset = natoms < 0
    natoms = abs(natoms)

    shape = []
    vectors = []
    for row in tokens[3:6]:
        parts = row.split()
        shape.append(abs(int(parts[0])))
        vectors.append([float(v) for v in parts[1:4]])

    symbols, coords = [], []
    inv = {v: k for k, v in ATOMIC_NUMBERS.items()}
    for row in tokens[6 : 6 + natoms]:
        parts = row.split()
        z = int(parts[0])
        symbols.append(inv.get(z, "X"))
        coords.append([float(v) for v in parts[2:5]])

    rest = tokens[6 + natoms :]
    if has_dset and rest:
        rest = rest[1:]
    values = np.array([float(v) for row in rest for v in row.split()])
    total = int(np.prod(shape))
    if values.size < total:
        raise ValueError(
            f"cube {os.path.basename(path)} has {values.size} values, expected {total}"
        )

    ang = 1.0 / BOHR_PER_ANGSTROM
    return {
        "comment": comment,
        "stamp": stamp,
        "data": values[:total].reshape(shape),
        "origin": origin * ang,
        "vectors": np.array(vectors) * ang,
        "symbols": symbols,
        "coords": np.array(coords) * ang if coords else np.zeros((0, 3)),
    }
